INSERT INTO Passengers (full_name, gender, nationality) VALUES
('Brandy Smith', 'Female', 'Ugandan'),
('Madison Castro', 'Female', 'Somali'),
('Ruth Heath', 'Female', 'Ugandan'),
('Bradley Smith', 'Male', 'South Sudanese'),
('Elizabeth Nunez', 'Female', 'Kenyan'),
('Jodi Fisher', 'Female', 'Ugandan'),
('Justin Shelton', 'Male', 'South Sudanese'),
('Teresa Sandoval', 'Female', 'Rwandan'),
('Victoria May', 'Female', 'Rwandan'),
('Nancy Holloway', 'Female', 'Rwandan'),
('Emily Williams', 'Female', 'Ethiopian'),
('Linda Moore', 'Female', 'Somali'),
('April Olson', 'Female', 'Ethiopian'),
('Richard Potter', 'Male', 'South Sudanese'),
('Joshua Ramirez', 'Male', 'Ugandan'),
('Veronica Dunlap', 'Female', 'Somali'),
('Kristine Chavez', 'Female', 'South Sudanese'),
('Laura Hernandez', 'Female', 'South Sudanese'),
('Andrea Alvarez', 'Female', 'Kenyan'),
('Rebecca Young', 'Female', 'Rwandan'),
('Pamela Swanson', 'Female', 'Kenyan'),
('Elizabeth Austin', 'Female', 'Rwandan'),
('Karen Allen', 'Female', 'Kenyan'),
('Danielle Jones', 'Female', 'South Sudanese'),
('Joshua Rodgers', 'Male', 'Rwandan'),
('Ray Dixon Jr.', 'Male', 'Ugandan'),
('Thomas Brown', 'Male', 'South Sudanese'),
('Erik Phillips', 'Male', 'Somali'),
('Michael Brennan', 'Male', 'Ugandan'),
('Holly Ryan', 'Female', 'South Sudanese'),
('Tiffany Rios', 'Female', 'Ethiopian'),
('Natalie Kelly', 'Female', 'Ugandan'),
('Tara Myers', 'Female', 'Kenyan'),
('Daniel Wilkins', 'Male', 'Ugandan'),
('James Patterson', 'Male', 'Rwandan'),
('Tina Vega', 'Female', 'Somali'),
('Frank Kelley', 'Male', 'Somali'),
('Jennifer Hart', 'Female', 'Kenyan'),
('Benjamin Walton', 'Male', 'Somali'),
('Leah Jones', 'Female', 'South Sudanese'),
('Shawn King', 'Male', 'Ugandan'),
('Henry Keith', 'Male', 'South Sudanese'),
('Jennifer Everett PhD', 'Female', 'South Sudanese'),
('Amy Bender', 'Female', 'Ugandan'),
('Erika Grant', 'Female', 'South Sudanese'),
('Lance Park', 'Male', 'Rwandan'),
('Claudia Bird', 'Female', 'Kenyan'),
('Heather Russell', 'Female', 'Rwandan'),
('Amanda Jacobs', 'Female', 'Somali'),
('Carlos Harper', 'Male', 'South Sudanese'),
('Fernando Valenzuela', 'Male', 'Somali'),
('Felicia Sanders', 'Female', 'Somali'),
('Pamela Owens', 'Female', 'Kenyan'),
('Jeanette Simmons', 'Female', 'South Sudanese'),
('Leslie Martin', 'Female', 'Rwandan'),
('Brandy Jefferson', 'Female', 'Kenyan'),
('Rebecca Douglas', 'Female', 'Rwandan'),
('Nancy Hodges', 'Female', 'Rwandan'),
('Jamie Thompson', 'Female', 'South Sudanese'),
('Roger Welch', 'Male', 'South Sudanese'),
('Jordan York', 'Male', 'Rwandan'),
('Michelle Scott', 'Female', 'Kenyan'),
('Sarah Dalton', 'Female', 'Somali'),
('James Stokes', 'Male', 'Rwandan'),
('Erin Peterson', 'Female', 'Ugandan'),
('Sarah Alexander', 'Female', 'Kenyan'),
('Paul Warren', 'Male', 'South Sudanese'),
('Brittany Crawford', 'Female', 'Ugandan'),
('David Mendoza', 'Male', 'South Sudanese'),
('John Leon', 'Male', 'Somali'),
('John Johnson', 'Male', 'Kenyan'),
('Carol Walker', 'Female', 'South Sudanese'),
('Veronica Clark', 'Female', 'Somali'),
('Elizabeth Oliver PhD', 'Female', 'Ethiopian'),
('Justin Norris', 'Male', 'Kenyan'),
('Carla Holder', 'Female', 'Kenyan'),
('Matthew May', 'Male', 'Rwandan'),
('Joshua Ryan', 'Male', 'South Sudanese'),
('Bryan Smith', 'Male', 'Somali'),
('Shane Johnson', 'Male', 'Somali'),
('Anita Garcia', 'Female', 'Ethiopian'),
('Brian Morrison', 'Male', 'Kenyan'),
('Joseph Lopez', 'Male', 'Rwandan'),
('Stephen Torres', 'Male', 'Somali'),
('Andrew Richard', 'Male', 'Ethiopian'),
('Lisa Reed', 'Female', 'Rwandan'),
('Sandra Cross', 'Female', 'Somali'),
('Frank Thomas', 'Male', 'Rwandan'),
('Traci Smith', 'Female', 'Ugandan'),
('Suzanne Todd', 'Female', 'South Sudanese'),
('Evan Jackson', 'Male', 'South Sudanese'),
('Alexandra Simmons', 'Female', 'Ethiopian'),
('Colleen Johnson', 'Female', 'Somali'),
('Donna Gonzalez', 'Female', 'Rwandan'),
('Adam Ferguson', 'Male', 'Kenyan'),
('Cathy Hutchinson', 'Female', 'Kenyan'),
('John Wheeler', 'Male', 'Somali'),
('Sarah Miller', 'Female', 'Rwandan'),
('Ashley Evans', 'Female', 'South Sudanese'),
('Terry Lopez', 'Female', 'Kenyan'),
('Meredith Keith', 'Female', 'Ethiopian'),
('Joshua Shaffer', 'Male', 'Somali'),
('Angela Price', 'Female', 'Kenyan'),
('Jimmy Burch', 'Male', 'Somali'),
('Nathan Roberts', 'Male', 'Rwandan'),
('Alexander Pierce', 'Male', 'Kenyan'),
('Daniel Evans', 'Male', 'Rwandan'),
('Nicole Ramsey', 'Female', 'Rwandan'),
('Gregory Espinoza', 'Male', 'Kenyan'),
('Jill Castaneda', 'Female', 'Kenyan'),
('Amanda Mendoza', 'Female', 'Rwandan'),
('Jaclyn Wright', 'Female', 'Ugandan'),
('Julia Hernandez', 'Female', 'Ethiopian'),
('Jenny Shepherd', 'Female', 'Rwandan'),
('Colleen Calderon', 'Female', 'Somali'),
('Shelia Tanner', 'Female', 'Ugandan'),
('Mrs. Amanda Gray', 'Female', 'Ugandan'),
('Chelsea Fisher', 'Female', 'Kenyan'),
('Amanda Bowman', 'Female', 'Rwandan'),
('Katherine Henry', 'Female', 'Kenyan'),
('Ryan Hunter', 'Male', 'Ugandan'),
('Daniel Austin', 'Male', 'South Sudanese'),
('Julie Moore', 'Female', 'Somali'),
('Emily Leach', 'Female', 'Ethiopian'),
('Ann Hernandez', 'Female', 'Kenyan'),
('Todd Novak', 'Male', 'Ethiopian'),
('Katherine Carey', 'Female', 'Rwandan'),
('Lisa Brooks', 'Female', 'South Sudanese'),
('Matthew Silva', 'Male', 'Ethiopian'),
('Karen Rowe', 'Female', 'South Sudanese'),
('Brenda Carroll', 'Female', 'Somali'),
('Julia Dixon', 'Female', 'South Sudanese'),
('Henry Williams', 'Male', 'Kenyan'),
('Robert Garcia', 'Male', 'Kenyan'),
('Christian Vazquez', 'Male', 'Ugandan'),
('James Booth', 'Male', 'Somali'),
('John Carpenter', 'Male', 'Rwandan'),
('Douglas Ruiz', 'Male', 'Ethiopian'),
('Tonya Taylor', 'Female', 'Ugandan'),
('Daniel Scott', 'Male', 'Kenyan'),
('Henry Parker', 'Male', 'Ethiopian'),
('Elizabeth Morse MD', 'Female', 'Ugandan'),
('Travis Donovan', 'Male', 'Kenyan'),
('Alexandra Dunlap', 'Female', 'Kenyan'),
('David Carroll', 'Male', 'Rwandan'),
('Rachel Gutierrez', 'Female', 'Somali'),
('Stephen Brown', 'Male', 'Kenyan'),
('Jeremiah Odonnell', 'Male', 'South Sudanese'),
('Dr. Robin Hill', 'Female', 'Kenyan'),
('Patricia Black', 'Female', 'Ugandan'),
('Grant Richmond', 'Male', 'Kenyan'),
('Joe Lang', 'Male', 'Ethiopian'),
('Timothy Jackson', 'Male', 'Rwandan'),
('Patricia Lara', 'Female', 'South Sudanese'),
('Brandon Phillips', 'Male', 'Ugandan'),
('David Morse', 'Male', 'Rwandan'),
('Erik Miller', 'Male', 'Ethiopian'),
('Michael Allison', 'Male', 'Kenyan'),
('Steven Osborne', 'Male', 'Ugandan'),
('Brett Allen', 'Male', 'Ugandan'),
('Susan Morris', 'Female', 'Rwandan'),
('Nicole Villarreal', 'Female', 'Somali'),
('Stacy Pugh', 'Female', 'Ethiopian'),
('Ann Benjamin DVM', 'Female', 'Somali'),
('Samuel Christensen', 'Male', 'Somali'),
('Bradley Barnes', 'Male', 'Somali'),
('Jerry Grant', 'Male', 'Somali'),
('Maria Alvarez', 'Female', 'Ugandan'),
('Miss Laura Brooks', 'Female', 'Kenyan'),
('Brian Murray', 'Male', 'Kenyan'),
('William Wright', 'Male', 'Somali'),
('Joshua Martinez', 'Male', 'Rwandan'),
('Wayne Robinson', 'Male', 'Rwandan'),
('Angel Joseph', 'Female', 'Ethiopian'),
('Lawrence Cabrera', 'Male', 'Somali'),
('Miss Elizabeth Duffy', 'Female', 'Kenyan'),
('Brian Barker', 'Male', 'Somali'),
('Carla Barron', 'Female', 'Ethiopian'),
('Wendy Walls', 'Female', 'South Sudanese'),
('James Jones', 'Male', 'Ethiopian'),
('Krystal Mason', 'Female', 'Kenyan'),
('Nicole Baldwin', 'Female', 'Somali'),
('Courtney Lee', 'Female', 'Somali'),
('Susan Cohen', 'Female', 'Ugandan'),
('Jose Dickerson', 'Male', 'Rwandan'),
('Robert Jones', 'Male', 'South Sudanese'),
('Margaret Reyes', 'Female', 'Somali'),
('Michael Lynch', 'Male', 'Somali'),
('Marvin Howe', 'Male', 'Kenyan'),
('Jacob Morgan', 'Male', 'Ethiopian'),
('Gloria Lee', 'Female', 'South Sudanese'),
('Dana Miller', 'Female', 'Rwandan'),
('Anthony Morrow', 'Male', 'Ugandan'),
('Michelle Thomas', 'Female', 'Ethiopian'),
('Tyler Wright', 'Male', 'Ugandan'),
('Bradley Henderson', 'Male', 'Somali'),
('Logan Williams', 'Male', 'Ethiopian'),
('Patrick Johnson', 'Male', 'Ethiopian'),
('Michael Harris', 'Male', 'Somali'),
('Rachel Howell', 'Female', 'Somali'),
('Timothy Ramos', 'Male', 'South Sudanese'),
('Sherry Smith DDS', 'Female', 'Kenyan'),
('Joseph Kelly', 'Male', 'Ugandan'),
('Mike Howard', 'Male', 'Somali'),
('Elaine Smith', 'Female', 'South Sudanese'),
('Katrina Mora', 'Female', 'Kenyan'),
('Jason Martinez', 'Male', 'South Sudanese'),
('Timothy Pitts', 'Male', 'Kenyan'),
('Mark Howard', 'Male', 'Somali'),
('Natalie Paul', 'Female', 'Ugandan'),
('Donna Bauer', 'Female', 'Kenyan'),
('Brianna Parker', 'Female', 'Ethiopian'),
('Michael White', 'Male', 'Rwandan'),
('Charles Holmes', 'Male', 'Ethiopian'),
('Colleen Mann', 'Female', 'South Sudanese'),
('Michael Novak', 'Male', 'Kenyan'),
('Krystal Wade', 'Female', 'Ethiopian'),
('Megan Watson', 'Female', 'Rwandan'),
('Kenneth Smith', 'Male', 'Somali'),
('Samantha Clark', 'Female', 'Ugandan'),
('Penny Mitchell', 'Female', 'Rwandan'),
('Barbara Wright', 'Female', 'Rwandan'),
('Jonathan Davis', 'Male', 'South Sudanese'),
('Melissa Rojas', 'Female', 'Ethiopian'),
('Nicole Soto', 'Female', 'Ugandan'),
('Richard King', 'Male', 'Rwandan'),
('Cheryl Reyes', 'Female', 'Rwandan'),
('Christopher Lawson', 'Male', 'South Sudanese'),
('Patrick Wright', 'Male', 'Rwandan'),
('Morgan Moore', 'Female', 'Kenyan'),
('Erica Howard', 'Female', 'Rwandan'),
('Kelli Mclean', 'Female', 'South Sudanese'),
('Karen Cardenas', 'Female', 'Ethiopian'),
('Ryan Ramsey', 'Male', 'Ethiopian'),
('Patricia Rodriguez', 'Female', 'Ethiopian'),
('Michael Harrison', 'Male', 'Ugandan'),
('Christopher Clark', 'Male', 'Rwandan'),
('Matthew Martinez', 'Male', 'Kenyan'),
('Victor Lopez', 'Male', 'Kenyan'),
('William Jackson', 'Male', 'Rwandan'),
('Corey Lewis', 'Male', 'Ugandan'),
('Melissa Fields', 'Female', 'South Sudanese'),
('Patrick Turner', 'Male', 'Rwandan'),
('Andrea Benton', 'Female', 'Somali'),
('Mary Nelson', 'Female', 'Ugandan'),
('Terry Dean', 'Male', 'Ugandan'),
('Angela Bradley', 'Female', 'Ethiopian'),
('Eric Wilson', 'Male', 'Somali'),
('Cody Ramsey', 'Male', 'Somali'),
('Caitlin Gutierrez', 'Female', 'South Sudanese'),
('Krista Robertson', 'Female', 'Ugandan'),
('Jonathan Gibson', 'Male', 'South Sudanese'),
('Katie Bond', 'Female', 'Rwandan'),
('Amy Patterson', 'Female', 'Kenyan'),
('James Hart', 'Male', 'Kenyan'),
('Karen Cannon', 'Female', 'Ethiopian'),
('Mr. William Bell', 'Male', 'South Sudanese'),
('Kenneth Smith', 'Male', 'Ethiopian'),
('Juan Perry', 'Male', 'Rwandan'),
('Jacob Logan', 'Male', 'Somali'),
('David Willis', 'Male', 'Ethiopian'),
('Gail Jackson', 'Female', 'Ethiopian'),
('Natalie Sharp', 'Female', 'Rwandan'),
('Vanessa Chapman', 'Female', 'Somali'),
('Matthew Johnson', 'Male', 'Ugandan'),
('Shannon George', 'Female', 'Kenyan'),
('Denise Graham', 'Female', 'Rwandan'),
('Jamie Woodward', 'Female', 'Ethiopian'),
('Ariel Waters', 'Female', 'Somali'),
('William Suarez', 'Male', 'South Sudanese'),
('Christopher Wade', 'Male', 'South Sudanese'),
('Heather Hoffman', 'Female', 'Ugandan'),
('Sara Harrison', 'Female', 'Kenyan'),
('Ashley Petty', 'Female', 'Ugandan'),
('Kristen Murillo', 'Female', 'Ethiopian'),
('Heather Holmes', 'Female', 'Rwandan'),
('April Holt', 'Female', 'Kenyan'),
('Claudia George', 'Female', 'Rwandan'),
('Rebecca Johnson', 'Female', 'Rwandan'),
('Jane Chavez', 'Female', 'Rwandan'),
('Kathleen Holt', 'Female', 'Ethiopian'),
('William Clark', 'Male', 'Ugandan'),
('Bryan Smith', 'Male', 'South Sudanese'),
('Victoria Bowen', 'Female', 'Somali'),
('Mark Jimenez', 'Male', 'Somali'),
('Kevin Harris', 'Male', 'Somali'),
('Christopher Bush', 'Male', 'South Sudanese'),
('Danny Wright', 'Male', 'Somali'),
('Kristen Hudson', 'Female', 'Ethiopian'),
('David Murphy', 'Male', 'Rwandan'),
('Dean Simon', 'Male', 'Ugandan'),
('Caroline Porter', 'Female', 'Somali'),
('Bryan Lee', 'Male', 'Ethiopian'),
('Steven Stevens', 'Male', 'South Sudanese'),
('Patrick Lawson', 'Male', 'Kenyan'),
('James Johnson', 'Male', 'Ugandan'),
('Vanessa Johnson', 'Female', 'South Sudanese'),
('Sarah Frye', 'Female', 'Ethiopian'),
('Austin Porter', 'Male', 'Kenyan'),
('Marisa Macdonald', 'Female', 'Somali'),
('Barry Hogan', 'Male', 'Ugandan'),
('Michael Williams', 'Male', 'Ugandan'),
('Robert Arias', 'Male', 'Ugandan'),
('David Page', 'Male', 'Ethiopian'),
('Gina Rush', 'Female', 'Kenyan'),
('John Ramirez PhD', 'Male', 'South Sudanese'),
('Shane Wilkinson', 'Male', 'Somali'),
('Jessica Thomas', 'Female', 'South Sudanese'),
('Michael Bass', 'Male', 'Rwandan'),
('Jeffrey Hays', 'Male', 'Rwandan'),
('Brian Compton', 'Male', 'Somali'),
('John Lee', 'Male', 'South Sudanese'),
('Julie Garcia', 'Female', 'South Sudanese'),
('Michael Morales', 'Male', 'South Sudanese'),
('Casey Clark', 'Male', 'South Sudanese'),
('April Olson', 'Female', 'Ethiopian'),
('Carol Stewart', 'Female', 'South Sudanese'),
('Victoria Mercer', 'Female', 'Kenyan'),
('Daniel Thomas', 'Male', 'Somali'),
('Ryan Allen', 'Male', 'Ethiopian'),
('Veronica Griffin', 'Female', 'South Sudanese'),
('Paul Wyatt', 'Male', 'Kenyan'),
('Mia Whitney', 'Female', 'Ethiopian'),
('Charles Miller', 'Male', 'Ugandan'),
('Anthony Holmes', 'Male', 'Rwandan'),
('Jordan Price', 'Male', 'Kenyan'),
('Joseph Aguilar', 'Male', 'Kenyan'),
('Lindsay Boyd', 'Female', 'Ugandan'),
('Caroline Wood', 'Female', 'Kenyan'),
('Tammy Johnson', 'Female', 'Ugandan'),
('Vincent Peterson', 'Male', 'South Sudanese'),
('Michael Harris', 'Male', 'South Sudanese'),
('Lisa Pugh', 'Female', 'Somali'),
('Justin Gonzalez', 'Male', 'Kenyan'),
('Mariah Curtis', 'Female', 'Rwandan'),
('David Robinson', 'Male', 'Rwandan'),
('Carrie Shelton', 'Female', 'Somali'),
('Victoria Houston', 'Female', 'Kenyan'),
('Timothy Thomas', 'Male', 'Kenyan'),
('Laura Rich', 'Female', 'Ugandan'),
('Jennifer Bentley', 'Female', 'Ethiopian'),
('Patrick Hernandez', 'Male', 'Rwandan'),
('Christopher Morales', 'Male', 'South Sudanese'),
('Jonathan Bennett', 'Male', 'Kenyan'),
('Bryan Berry', 'Male', 'Rwandan'),
('Joanna Curry', 'Female', 'Somali'),
('Kathleen Hodges', 'Female', 'Ethiopian'),
('Stephanie Velasquez', 'Female', 'South Sudanese'),
('Joanne Fletcher', 'Female', 'Kenyan'),
('Joseph Butler', 'Male', 'Ethiopian'),
('Erika Ford', 'Female', 'Somali'),
('Jessica Martinez', 'Female', 'Rwandan'),
('Allison Anderson', 'Female', 'Kenyan'),
('Brian Andrews', 'Male', 'Somali'),
('Cynthia Choi', 'Female', 'South Sudanese'),
('Stacy Miller', 'Female', 'Ugandan'),
('Mikayla Garrett', 'Female', 'South Sudanese'),
('Rebecca Walton', 'Female', 'South Sudanese'),
('Michael Williams', 'Male', 'Ugandan'),
('Chelsea Aguilar', 'Female', 'South Sudanese'),
('Zachary Collins', 'Male', 'Ethiopian'),
('James Gregory', 'Male', 'South Sudanese'),
('Jeffery Cooper', 'Male', 'Ethiopian'),
('Christopher Orozco', 'Male', 'Kenyan'),
('Melody Hull', 'Female', 'Rwandan'),
('Angela Warren', 'Female', 'Somali'),
('Deborah Sullivan', 'Female', 'Somali'),
('Dr. Ashley Conner DDS', 'Female', 'Ugandan'),
('William Lee', 'Male', 'Kenyan'),
('Traci Santana', 'Female', 'Ugandan'),
('Mrs. Barbara Velez', 'Female', 'Ethiopian'),
('Anthony Waters', 'Male', 'Somali'),
('Kevin Rodgers', 'Male', 'Kenyan'),
('Wayne Jennings', 'Male', 'Rwandan'),
('Corey Jones', 'Male', 'Kenyan'),
('Larry Duncan', 'Male', 'Rwandan'),
('Julie Waters', 'Female', 'Rwandan'),
('Roger Allen', 'Male', 'Kenyan'),
('Julie Duffy', 'Female', 'Ugandan'),
('Caitlin Miller', 'Female', 'Ugandan'),
('Melissa Day', 'Female', 'Ethiopian'),
('Heidi Oneill', 'Female', 'Ugandan'),
('Angela Garcia', 'Female', 'Ethiopian'),
('Melissa Gray', 'Female', 'Rwandan'),
('Phillip Smith', 'Male', 'South Sudanese'),
('Linda Stephens', 'Female', 'Ethiopian'),
('Rhonda Stevenson', 'Female', 'Ugandan'),
('Kyle Perez', 'Male', 'Somali'),
('Zachary Harmon', 'Male', 'Somali'),
('Aaron Wang', 'Male', 'Ugandan'),
('Jo Allen', 'Female', 'Ugandan'),
('Rachel Mitchell', 'Female', 'South Sudanese'),
('Emily Fowler', 'Female', 'Ethiopian'),
('Terri Austin', 'Female', 'Ugandan'),
('Trevor Smith', 'Male', 'Rwandan'),
('Brian Carroll', 'Male', 'Ugandan'),
('David White', 'Male', 'Kenyan'),
('Brian Valencia', 'Male', 'Rwandan'),
('Adam Peterson', 'Male', 'Ethiopian'),
('Miss Susan Pennington', 'Female', 'Rwandan'),
('Paige Cameron DDS', 'Female', 'Somali'),
('Megan Johnson', 'Female', 'Kenyan'),
('Brenda Cooper', 'Female', 'Kenyan'),
('Carol Paul', 'Female', 'Rwandan'),
('Roger Grimes', 'Male', 'Kenyan'),
('Keith Palmer', 'Male', 'Somali'),
('Kelly Monroe', 'Female', 'Somali'),
('Marcus Myers', 'Male', 'Ugandan'),
('Timothy Smith', 'Male', 'South Sudanese'),
('Kenneth Smith', 'Male', 'South Sudanese'),
('James Webster', 'Male', 'South Sudanese'),
('Ryan Myers', 'Male', 'South Sudanese'),
('Jeremiah Martin', 'Male', 'Ugandan'),
('Luis Rhodes', 'Male', 'Somali'),
('Ronald Carey', 'Male', 'Ugandan'),
('Stephen Johns', 'Male', 'Kenyan'),
('Meghan Gray', 'Female', 'Kenyan'),
('Terry Mora', 'Male', 'Kenyan'),
('Christopher Delgado DDS', 'Male', 'Rwandan'),
('Jonathan Miller', 'Male', 'Ethiopian'),
('Jeremiah Davis', 'Male', 'Somali'),
('Daniel Johnson', 'Male', 'Ethiopian'),
('Brittany Johnson', 'Female', 'Kenyan'),
('Matthew Guzman Jr.', 'Male', 'Somali'),
('Keith Martinez', 'Male', 'Rwandan'),
('Melissa Pennington', 'Female', 'Kenyan'),
('Emily Snyder', 'Female', 'Somali'),
('Andrea Decker', 'Female', 'Ugandan'),
('Kimberly Wyatt', 'Female', 'Somali'),
('Eric Smith', 'Male', 'Somali'),
('Andrew Gray Jr.', 'Male', 'Ugandan'),
('Charles Cooper', 'Male', 'Rwandan'),
('Rhonda Gray', 'Female', 'Somali'),
('John Ochoa', 'Male', 'Ugandan'),
('Aaron Mcpherson', 'Male', 'Kenyan'),
('Laura Baxter', 'Female', 'Rwandan'),
('Steven Oliver', 'Male', 'Somali'),
('Courtney Moyer', 'Female', 'Ethiopian'),
('Julia Ward', 'Female', 'Kenyan'),
('John Suarez', 'Male', 'Ethiopian'),
('Cory Cole', 'Male', 'Ethiopian'),
('Clayton Brooks', 'Male', 'Ethiopian'),
('Brittney Johnson', 'Female', 'Kenyan'),
('Kevin Baker', 'Male', 'Ethiopian'),
('Mia Nguyen', 'Female', 'Rwandan'),
('Amber Cook', 'Female', 'Rwandan'),
('Natalie Cruz', 'Female', 'Kenyan'),
('Susan Hamilton', 'Female', 'Rwandan'),
('Tyler Garrett', 'Male', 'Somali'),
('Patricia White', 'Female', 'Ethiopian'),
('Scott Zuniga', 'Male', 'Ugandan'),
('Ashley Riggs', 'Female', 'Rwandan'),
('Paul Mccoy', 'Male', 'South Sudanese'),
('Luis Mcknight', 'Male', 'Somali'),
('Dawn Peterson', 'Female', 'Ethiopian'),
('Kendra Powell', 'Female', 'Rwandan'),
('David Webb', 'Male', 'South Sudanese'),
('Melanie Roberts', 'Female', 'South Sudanese'),
('Lisa Hawkins', 'Female', 'Kenyan'),
('Mr. Joshua Perez MD', 'Male', 'South Sudanese'),
('Anne Little', 'Female', 'Rwandan'),
('Joseph Stout', 'Male', 'South Sudanese'),
('Whitney Reyes', 'Female', 'South Sudanese'),
('Kylie Aguilar', 'Female', 'Kenyan'),
('Peggy Sherman', 'Female', 'Somali'),
('Darrell Aguilar', 'Male', 'Rwandan'),
('James Nielsen', 'Male', 'Rwandan'),
('Adam Brown', 'Male', 'Rwandan'),
('Kurt Anderson', 'Male', 'Ugandan'),
('Michelle Williams', 'Female', 'Ethiopian'),
('Sarah Bush', 'Female', 'Somali'),
('Robert Moore', 'Male', 'Ethiopian'),
('Peter Preston', 'Male', 'Somali'),
('Lisa Frazier', 'Female', 'Somali'),
('Christopher George', 'Male', 'Ugandan'),
('Laura Powers', 'Female', 'Ugandan'),
('Chase Clark', 'Male', 'Kenyan'),
('Trevor Avila', 'Male', 'Ethiopian'),
('Briana Jones', 'Female', 'South Sudanese'),
('Chad Robinson', 'Male', 'Ethiopian'),
('Sandra Todd', 'Female', 'Ethiopian'),
('Jill Peterson', 'Female', 'Somali'),
('Ms. Shelby Page', 'Female', 'Somali'),
('Michelle Rivera', 'Female', 'Ugandan'),
('Crystal Hanna', 'Female', 'Ugandan'),
('Dominic Rivera', 'Male', 'Somali'),
('Wendy Francis', 'Female', 'Kenyan'),
('Barbara Edwards', 'Female', 'Ugandan'),
('Julia Rowland PhD', 'Female', 'Ethiopian'),
('Amy Barron', 'Female', 'Ethiopian'),
('David Diaz', 'Male', 'Ugandan'),
('Jennifer Wilson', 'Female', 'Ethiopian'),
('Francis Ibarra', 'Male', 'Somali'),
('Manuel Baker', 'Male', 'Rwandan'),
('Teresa Thomas', 'Female', 'Ugandan'),
('Danny Mendoza', 'Male', 'Ethiopian'),
('Hunter Best', 'Male', 'Somali'),
('Christian Leach', 'Male', 'Somali'),
('Mary Williams', 'Female', 'Somali'),
('Jennifer Parks', 'Female', 'Ugandan'),
('John Fuller', 'Male', 'Ethiopian'),
('Jim Mendoza', 'Male', 'Ugandan'),
('Darin Hanson', 'Male', 'Somali'),
('Kevin Lewis', 'Male', 'Rwandan'),
('Cheryl Barnett', 'Female', 'South Sudanese'),
('Anthony Tucker', 'Male', 'South Sudanese'),
('John Meyer', 'Male', 'Ugandan'),
('Wendy Henson', 'Female', 'Ugandan'),
('Mr. Juan West DDS', 'Male', 'Ethiopian'),
('Judith Robles', 'Female', 'Ethiopian'),
('John Greene', 'Male', 'Rwandan'),
('Lisa Gordon', 'Female', 'Kenyan'),
('Lori Williams', 'Female', 'Somali'),
('Mariah Russell', 'Female', 'Rwandan'),
('Brian Bush', 'Male', 'Kenyan'),
('Jeffrey Hunter', 'Male', 'South Sudanese'),
('Jeffrey Wright', 'Male', 'Rwandan'),
('Jacqueline Yang', 'Female', 'Ugandan'),
('Gabriel Owens', 'Male', 'Ugandan'),
('Victoria Barton', 'Female', 'Rwandan'),
('Thomas Gallagher', 'Male', 'Somali'),
('Robert Payne DVM', 'Male', 'Somali'),
('Evan Ryan', 'Male', 'Rwandan'),
('Evan Jones', 'Male', 'Somali'),
('Laura Porter', 'Female', 'Somali'),
('Sarah Wilkinson', 'Female', 'Ethiopian'),
('Jason Carey', 'Male', 'Rwandan'),
('Christopher Shaw', 'Male', 'Somali'),
('Emily Odonnell', 'Female', 'Ugandan'),
('Brandon Fitzpatrick', 'Male', 'Somali'),
('Zachary Ward', 'Male', 'South Sudanese'),
('Raymond Martinez', 'Male', 'South Sudanese'),
('Todd Drake', 'Male', 'Kenyan'),
('Joshua Frank', 'Male', 'Somali'),
('Anna Mitchell', 'Female', 'Kenyan'),
('Michael Gomez', 'Male', 'Somali'),
('Phillip Brown', 'Male', 'Ugandan'),
('Stacey Conley', 'Female', 'Somali'),
('Sarah Kemp', 'Female', 'Somali'),
('Richard Henderson', 'Male', 'Ugandan'),
('Keith Olson', 'Male', 'Rwandan'),
('Jon Mccormick', 'Male', 'Kenyan'),
('James Ellis', 'Male', 'Ethiopian'),
('Amanda Klein', 'Female', 'Kenyan'),
('Steven Hart', 'Male', 'Somali'),
('Casey Nelson', 'Male', 'South Sudanese'),
('Michael Pearson', 'Male', 'Ethiopian'),
('Jeremy Curry', 'Male', 'Somali'),
('Jonathan Ho', 'Male', 'South Sudanese'),
('Aaron Jones', 'Male', 'Rwandan'),
('Hector Buckley', 'Male', 'Rwandan'),
('Jennifer Ellis', 'Female', 'Ethiopian'),
('Jennifer Ochoa', 'Female', 'South Sudanese'),
('Katie Copeland', 'Female', 'Kenyan'),
('Mr. Joshua Kim', 'Male', 'Kenyan'),
('Christopher Fisher', 'Male', 'Rwandan'),
('John Joseph', 'Male', 'Ugandan'),
('Corey Hampton', 'Male', 'South Sudanese'),
('Jennifer Ellis', 'Female', 'Kenyan'),
('Nicholas Patterson', 'Male', 'Rwandan'),
('Stephanie Smith', 'Female', 'Rwandan'),
('Tamara Parks', 'Female', 'Ugandan'),
('Katrina Graham', 'Female', 'South Sudanese'),
('Lisa Cain', 'Female', 'Ugandan'),
('Colin Hayes', 'Male', 'South Sudanese'),
('Robert Perez', 'Male', 'Somali'),
('Julie Hopkins', 'Female', 'Somali'),
('Victoria Sawyer', 'Female', 'South Sudanese'),
('Mario Foster', 'Male', 'Ethiopian'),
('Nancy Monroe', 'Female', 'Kenyan'),
('Eric Navarro', 'Male', 'Somali'),
('Jessica Bautista', 'Female', 'Somali'),
('Jackie Fuller', 'Female', 'Somali'),
('Karen Wallace', 'Female', 'Rwandan'),
('Susan Green', 'Female', 'Kenyan'),
('Andrew Martin', 'Male', 'South Sudanese'),
('Evan Petty', 'Male', 'Ugandan'),
('Randy Mitchell', 'Male', 'Ugandan'),
('Alexander Hicks', 'Male', 'South Sudanese'),
('Richard Johnson', 'Male', 'Rwandan'),
('Sabrina Schneider', 'Female', 'South Sudanese'),
('Brenda Stevens', 'Female', 'Rwandan'),
('David Robbins', 'Male', 'Somali'),
('Glenn Medina', 'Male', 'Somali'),
('Connor Anderson', 'Male', 'Ethiopian'),
('Patricia Diaz', 'Female', 'South Sudanese'),
('Hannah Montgomery', 'Female', 'Ugandan'),
('Daniel Brown', 'Male', 'Rwandan'),
('Olivia Price', 'Female', 'Ugandan'),
('Diana Hall', 'Female', 'Rwandan'),
('Kimberly Vance', 'Female', 'Kenyan'),
('Andrew Young', 'Male', 'Rwandan'),
('Robin Hoover', 'Female', 'Kenyan'),
('Cody Wood', 'Male', 'Kenyan'),
('Diane Martinez', 'Female', 'Kenyan'),
('James Berger DDS', 'Male', 'South Sudanese'),
('Brian Miller', 'Male', 'Ugandan'),
('Michael Garcia', 'Male', 'Rwandan'),
('Kevin Schultz', 'Male', 'Somali'),
('Daniel Stafford', 'Male', 'South Sudanese'),
('William Edwards', 'Male', 'Somali'),
('Courtney Barnes', 'Female', 'Ugandan'),
('Joshua Santos', 'Male', 'Kenyan'),
('Dave Cole', 'Male', 'South Sudanese'),
('Michael Shelton', 'Male', 'Ugandan'),
('Thomas Washington', 'Male', 'Somali'),
('Shannon Lewis', 'Female', 'Ugandan'),
('Andrea Esparza', 'Female', 'Kenyan'),
('Rachel Rogers', 'Female', 'Ugandan'),
('James Martin', 'Male', 'Kenyan'),
('Anthony Martinez', 'Male', 'Rwandan'),
('Nicole Gentry', 'Female', 'Somali'),
('Daniel Hanna', 'Male', 'Rwandan'),
('Joel Mckinney', 'Male', 'South Sudanese'),
('Amanda Brown', 'Female', 'Kenyan'),
('Daniel Miller', 'Male', 'Rwandan'),
('John Graves', 'Male', 'Ugandan'),
('Lauren Olson', 'Female', 'Ethiopian'),
('Ralph Mcdonald', 'Male', 'Kenyan'),
('James Jones', 'Male', 'Somali'),
('Timothy Robinson', 'Male', 'South Sudanese'),
('Laura Sosa', 'Female', 'Rwandan'),
('Yesenia Thomas', 'Female', 'Kenyan'),
('Mr. Michael Wyatt', 'Male', 'Somali'),
('Barbara Vang', 'Female', 'South Sudanese'),
('Brittany Lucas', 'Female', 'Kenyan'),
('Destiny Alexander', 'Female', 'Kenyan'),
('Amber Young', 'Female', 'Ugandan'),
('John Burton', 'Male', 'Rwandan'),
('Cassandra Warren', 'Female', 'Ethiopian'),
('Jason Miller', 'Male', 'Rwandan'),
('James Gilmore', 'Male', 'South Sudanese'),
('Samuel Jackson', 'Male', 'South Sudanese'),
('Caitlin Fernandez', 'Female', 'Ethiopian'),
('Terrance Ruiz', 'Male', 'Somali'),
('Laura Brennan', 'Female', 'South Sudanese'),
('Luis Hardy', 'Male', 'Kenyan'),
('Daniel Barrett', 'Male', 'Somali'),
('David Brown', 'Male', 'Kenyan'),
('Brian Rodriguez', 'Male', 'South Sudanese'),
('Kevin Garcia', 'Male', 'South Sudanese'),
('Evan Brown', 'Male', 'Kenyan'),
('Alvin Hill', 'Male', 'Ugandan'),
('Alexander Waters', 'Male', 'Ugandan'),
('Mario Harper', 'Male', 'Ethiopian'),
('Kaitlin Herrera', 'Female', 'Kenyan'),
('Kristen Ryan', 'Female', 'South Sudanese'),
('James Stevens', 'Male', 'Kenyan'),
('Gina Anthony', 'Female', 'Ethiopian'),
('Carrie Jackson', 'Female', 'Kenyan'),
('Michelle Palmer', 'Female', 'Ethiopian'),
('Lori Gonzalez', 'Female', 'South Sudanese'),
('Kevin Cooper', 'Male', 'Kenyan'),
('Emily Norton', 'Female', 'South Sudanese'),
('James Fields', 'Male', 'Somali'),
('William Schmidt', 'Male', 'Ugandan'),
('Megan Palmer', 'Female', 'Rwandan'),
('Beth Miller', 'Female', 'Somali'),
('Katelyn Fischer', 'Female', 'South Sudanese'),
('Julie Smith', 'Female', 'Ethiopian'),
('Kristina Owens', 'Female', 'Rwandan'),
('Brittany Brown', 'Female', 'Ugandan'),
('Cassandra Carroll', 'Female', 'Ethiopian'),
('Isaiah Copeland', 'Male', 'Somali'),
('Jessica Grimes', 'Female', 'Somali'),
('Larry Roth', 'Male', 'South Sudanese'),
('Beth Crawford', 'Female', 'Kenyan'),
('Nathan Gay', 'Male', 'Ethiopian'),
('Tiffany Travis', 'Female', 'Kenyan'),
('Sean Gonzales', 'Male', 'Somali'),
('Alex Brown', 'Male', 'Somali'),
('Mrs. Wendy Mendoza', 'Female', 'South Sudanese'),
('Jonathan Martin', 'Male', 'South Sudanese'),
('Scott Webb', 'Male', 'Somali'),
('Mark White', 'Male', 'Kenyan'),
('Brenda Maxwell', 'Female', 'Ethiopian'),
('Michael Wilson', 'Male', 'Ethiopian'),
('Paul Manning', 'Male', 'Rwandan'),
('Anna York', 'Female', 'Somali'),
('Cynthia Lane', 'Female', 'Ethiopian'),
('Jessica Jordan', 'Female', 'South Sudanese'),
('Allison Smith', 'Female', 'Ugandan'),
('Lori Lowe', 'Female', 'Somali'),
('Alicia Fischer', 'Female', 'Ugandan'),
('Kathy Patel', 'Female', 'Rwandan'),
('Kenneth Brooks', 'Male', 'South Sudanese'),
('Cory Carpenter', 'Male', 'Somali'),
('Robert Moran', 'Male', 'Ethiopian'),
('Andrea Smith', 'Female', 'Rwandan'),
('Miranda Hayes', 'Female', 'South Sudanese'),
('Edward Rasmussen', 'Male', 'Kenyan'),
('Michael Graves', 'Male', 'Somali'),
('Julie Hobbs', 'Female', 'Ugandan'),
('John Mitchell', 'Male', 'Rwandan'),
('Stephanie Turner', 'Female', 'Somali'),
('Adam Moon', 'Male', 'Ugandan'),
('William Johnson', 'Male', 'Rwandan'),
('Sierra Hall', 'Female', 'Ethiopian'),
('Jessica Lucas', 'Female', 'Kenyan'),
('Anthony Williams', 'Male', 'Kenyan'),
('Alison Williams', 'Female', 'Ugandan'),
('Steven Tran', 'Male', 'South Sudanese'),
('Christopher Tucker', 'Male', 'Kenyan'),
('Rebecca Harris', 'Female', 'Kenyan'),
('Mr. Antonio Acosta', 'Male', 'Kenyan'),
('Christopher Quinn', 'Male', 'Ethiopian'),
('Elizabeth Goodwin', 'Female', 'South Sudanese'),
('Cathy Rodgers', 'Female', 'Ethiopian'),
('Deborah Mcdonald', 'Female', 'Rwandan'),
('Michelle Terrell', 'Female', 'Ethiopian'),
('Vanessa Barnes', 'Female', 'Somali'),
('Alex Fowler', 'Male', 'Kenyan'),
('Melanie Owens', 'Female', 'Ugandan'),
('Allen Sullivan', 'Male', 'Rwandan'),
('Susan Graham', 'Female', 'Rwandan'),
('Jacob Blake', 'Male', 'Kenyan'),
('Mr. Corey West', 'Male', 'Somali'),
('Rebecca Lopez', 'Female', 'Kenyan'),
('Samantha Foster', 'Female', 'South Sudanese'),
('Kendra Perez', 'Female', 'Kenyan'),
('Nicholas Olsen', 'Male', 'Ugandan'),
('Wendy Rogers', 'Female', 'South Sudanese'),
('David Morris', 'Male', 'Ugandan'),
('Cynthia Carroll', 'Female', 'South Sudanese'),
('Calvin Leblanc', 'Male', 'Kenyan'),
('John Parker', 'Male', 'Kenyan'),
('Kevin Smith', 'Male', 'Ugandan'),
('Laurie Tate', 'Female', 'Ugandan'),
('Gregory Macdonald', 'Male', 'Somali'),
('Robert Lewis', 'Male', 'Somali'),
('David Velez', 'Male', 'Ethiopian'),
('Christine Jackson', 'Female', 'Ugandan'),
('Jeff Cohen', 'Male', 'South Sudanese'),
('Anthony Sutton', 'Male', 'South Sudanese'),
('Edwin Velez', 'Male', 'Ethiopian'),
('Valerie Long', 'Female', 'South Sudanese'),
('Stephen Kelly', 'Male', 'South Sudanese'),
('Donald Baker', 'Male', 'Rwandan'),
('Allison Patel', 'Female', 'Rwandan'),
('Alicia Roberts', 'Female', 'Ethiopian'),
('Jacob Graham', 'Male', 'South Sudanese'),
('Thomas Ramirez', 'Male', 'Somali'),
('Robin Jackson', 'Female', 'Kenyan'),
('Amanda Baxter', 'Female', 'Ethiopian'),
('Jonathan James', 'Male', 'Rwandan'),
('Morgan Booth', 'Female', 'Ethiopian'),
('Melissa Wilson', 'Female', 'Ethiopian'),
('Scott Stewart', 'Male', 'Kenyan'),
('Crystal Hancock', 'Female', 'Somali'),
('Paul Hayes DVM', 'Male', 'Rwandan'),
('Philip Schwartz', 'Male', 'Kenyan'),
('Karen Rivers', 'Female', 'Rwandan'),
('Bobby Haley', 'Male', 'Somali'),
('David Barnes', 'Male', 'Somali'),
('Nicole Quinn', 'Female', 'Somali'),
('Thomas Brennan', 'Male', 'Ethiopian'),
('Scott Matthews', 'Male', 'Kenyan'),
('Megan Nguyen DDS', 'Female', 'Rwandan'),
('Tammy Mendoza', 'Female', 'South Sudanese'),
('Don Horton', 'Male', 'South Sudanese'),
('Dennis Simmons', 'Male', 'South Sudanese'),
('Robert Finley', 'Male', 'Kenyan'),
('Carol Kennedy', 'Female', 'Kenyan'),
('Thomas Fowler', 'Male', 'South Sudanese'),
('Cynthia Williams', 'Female', 'Kenyan'),
('Jennifer Ochoa', 'Female', 'South Sudanese'),
('James Washington', 'Male', 'Somali'),
('Heather Mccoy', 'Female', 'Somali'),
('Sierra Soto', 'Female', 'Ethiopian'),
('Michelle Cain', 'Female', 'Kenyan'),
('Sheri Greer', 'Female', 'Kenyan'),
('Leroy Bryant', 'Male', 'Rwandan'),
('Melanie Moore', 'Female', 'Ugandan'),
('Anita Jones', 'Female', 'Ugandan'),
('April Richards', 'Female', 'Ugandan'),
('Jack Howard', 'Male', 'Somali'),
('Roberto Fleming', 'Male', 'Ethiopian'),
('Rita Miller', 'Female', 'Rwandan'),
('Kelsey Brown', 'Female', 'South Sudanese'),
('Jeffrey Kramer', 'Male', 'Kenyan'),
('Nicole Barnes', 'Female', 'Rwandan'),
('Mason Miller', 'Male', 'Ugandan'),
('Shelby Carlson', 'Female', 'Kenyan'),
('Dean Meyer', 'Male', 'Somali'),
('Alexis Porter', 'Female', 'Kenyan'),
('Jacqueline Guerra', 'Female', 'Kenyan'),
('Maria Lopez', 'Female', 'Ethiopian'),
('Jessica Cox', 'Female', 'Somali'),
('Megan Duncan', 'Female', 'Rwandan'),
('Suzanne Ramirez', 'Female', 'Kenyan'),
('Barbara Holloway', 'Female', 'Kenyan'),
('Mark Stephens', 'Male', 'Rwandan'),
('Joe Garcia', 'Male', 'South Sudanese'),
('Kyle Johnson', 'Male', 'Ugandan'),
('Richard Caldwell', 'Male', 'Ethiopian'),
('Tyler Welch', 'Male', 'Rwandan'),
('Alyssa Kennedy', 'Female', 'Ethiopian'),
('Kendra Griffin', 'Female', 'South Sudanese'),
('Larry Garner', 'Male', 'Rwandan'),
('Oscar Palmer', 'Male', 'Rwandan'),
('Frank Ray', 'Male', 'Kenyan'),
('Stephen Mason', 'Male', 'South Sudanese'),
('Ann Nelson', 'Female', 'Ugandan'),
('Mary Moss', 'Female', 'South Sudanese'),
('Adrienne Jones', 'Female', 'South Sudanese'),
('Nicolas Page', 'Male', 'Ugandan'),
('Steven Cunningham', 'Male', 'Ugandan'),
('Jeffrey Brown', 'Male', 'Rwandan'),
('Nancy Robertson', 'Female', 'Somali'),
('Steven Walters', 'Male', 'Somali'),
('Stephanie Fisher', 'Female', 'Ugandan'),
('Rebecca Williams', 'Female', 'Ethiopian'),
('Timothy Bean', 'Male', 'South Sudanese'),
('Maxwell Moreno', 'Male', 'Somali'),
('Rachel Fox', 'Female', 'South Sudanese'),
('Aaron Foster', 'Male', 'Somali'),
('Taylor Miller', 'Female', 'South Sudanese'),
('Caleb Conrad', 'Male', 'Kenyan'),
('Darrell Alvarez', 'Male', 'Somali'),
('Michelle Davis', 'Female', 'Ethiopian'),
('Jennifer Scott', 'Female', 'South Sudanese'),
('Natalie Savage', 'Female', 'Kenyan'),
('Jessica Watson', 'Female', 'Ugandan'),
('Lisa Mitchell', 'Female', 'Ethiopian'),
('Shane Lee', 'Male', 'Ethiopian'),
('Allison Hughes', 'Female', 'Ethiopian'),
('Nicholas Scott', 'Male', 'Rwandan'),
('Mark Bailey', 'Male', 'Kenyan'),
('Joshua Floyd', 'Male', 'South Sudanese'),
('Bailey Klein', 'Female', 'Rwandan'),
('Jack Jones', 'Male', 'Somali'),
('Michael Greer', 'Male', 'South Sudanese'),
('Pamela Roberts', 'Female', 'Kenyan'),
('Edward Carter', 'Male', 'Ethiopian'),
('Jodi Robinson', 'Female', 'South Sudanese'),
('Taylor Robinson', 'Female', 'Rwandan'),
('Becky Fletcher', 'Female', 'Somali'),
('David Yates', 'Male', 'Kenyan'),
('Stephanie Moreno', 'Female', 'South Sudanese'),
('Howard Butler', 'Male', 'Rwandan'),
('Stephanie Hernandez', 'Female', 'Somali'),
('Gina Campbell', 'Female', 'Rwandan'),
('William Hughes', 'Male', 'Rwandan'),
('Renee Neal', 'Female', 'Ugandan'),
('David Ford', 'Male', 'South Sudanese'),
('Eric Salazar', 'Male', 'Somali'),
('Toni Jackson', 'Female', 'South Sudanese'),
('Jeremy Douglas', 'Male', 'South Sudanese'),
('Emily Jones', 'Female', 'Somali'),
('Jose Hess', 'Male', 'Kenyan'),
('Wanda Adams MD', 'Female', 'Rwandan'),
('Jacqueline Williams', 'Female', 'South Sudanese'),
('Edward Clements', 'Male', 'Kenyan'),
('Kristen Patton', 'Female', 'Somali'),
('Danny Krueger', 'Male', 'Ethiopian'),
('Miranda Carter', 'Female', 'Somali'),
('Katherine Flores', 'Female', 'Ugandan'),
('Kathleen Carter', 'Female', 'Ethiopian'),
('Richard Sutton', 'Male', 'Rwandan'),
('Matthew White', 'Male', 'Ethiopian'),
('Madeline Cooper', 'Female', 'Kenyan'),
('Jared Cooper', 'Male', 'Ethiopian'),
('Andrea Smith', 'Female', 'Ugandan'),
('Joshua Wilkins', 'Male', 'Somali'),
('Sarah Hill', 'Female', 'Kenyan'),
('Michael Thomas', 'Male', 'Ethiopian'),
('Nancy Young', 'Female', 'Rwandan'),
('Vincent Roach', 'Male', 'Rwandan'),
('Jillian Johnson', 'Female', 'Rwandan'),
('Christopher Harris', 'Male', 'South Sudanese'),
('Richard Fisher', 'Male', 'Rwandan'),
('Terry Smith', 'Male', 'South Sudanese'),
('Tracy Garza', 'Female', 'Ugandan'),
('Morgan Leach', 'Female', 'Somali'),
('Faith Sanders', 'Female', 'Rwandan'),
('Stephanie Schmidt', 'Female', 'Rwandan'),
('Bethany Gray', 'Female', 'Ugandan'),
('Jose Alexander', 'Male', 'Somali'),
('Antonio Ellis', 'Male', 'Rwandan'),
('Christine Cole', 'Female', 'Somali'),
('Alfred Ward', 'Male', 'Ugandan'),
('Cory Mendoza', 'Male', 'South Sudanese'),
('Ryan Johnson', 'Male', 'Ethiopian'),
('Sara Richards', 'Female', 'Ethiopian'),
('Darrell Harris', 'Male', 'Ugandan'),
('Rhonda Wilkinson', 'Female', 'Rwandan'),
('Joseph Moore PhD', 'Male', 'Ethiopian'),
('Timothy Lang', 'Male', 'Ugandan'),
('Anthony Morgan', 'Male', 'Somali'),
('Gary Tran', 'Male', 'Ethiopian'),
('Dorothy Petty', 'Female', 'South Sudanese'),
('Karen Deleon', 'Female', 'Rwandan'),
('Jean Brown', 'Female', 'South Sudanese'),
('Jason Silva', 'Male', 'South Sudanese'),
('Jacob Sandoval', 'Male', 'Somali'),
('Martin Smith', 'Male', 'Somali'),
('Aaron Perkins', 'Male', 'Ugandan'),
('Deborah Gates', 'Female', 'South Sudanese'),
('Karen Silva', 'Female', 'Rwandan'),
('Tammy Miller', 'Female', 'Ethiopian'),
('Crystal Matthews', 'Female', 'South Sudanese'),
('Kimberly Williams', 'Female', 'South Sudanese'),
('Randall Montgomery', 'Male', 'Ugandan'),
('Ryan Williams', 'Male', 'Ethiopian'),
('Christina Schultz', 'Female', 'South Sudanese'),
('Ann Larsen', 'Female', 'South Sudanese'),
('Jeremy Nicholson', 'Male', 'Ugandan'),
('Trevor Richardson', 'Male', 'Ethiopian'),
('Harry Stewart', 'Male', 'South Sudanese'),
('Stephanie Cole', 'Female', 'South Sudanese'),
('Tiffany Johnson', 'Female', 'Rwandan'),
('Phyllis Lee', 'Female', 'Ethiopian'),
('Jessica Shannon', 'Female', 'Ethiopian'),
('Laura Leonard', 'Female', 'Kenyan'),
('Michele Lee', 'Female', 'Somali'),
('Carrie Gonzalez', 'Female', 'Somali'),
('Heather Jones', 'Female', 'South Sudanese'),
('Hayley Chang', 'Female', 'South Sudanese'),
('David Mcdonald', 'Male', 'Kenyan'),
('Brittany Francis', 'Female', 'Rwandan'),
('Jermaine Boyd', 'Male', 'Ethiopian'),
('Paige Reed', 'Female', 'Rwandan'),
('Dustin Ortiz', 'Male', 'Rwandan'),
('Sheila Bradford', 'Female', 'Ugandan'),
('Joel Rodriguez', 'Male', 'Somali'),
('Danielle Ward', 'Female', 'Kenyan'),
('Dominique Edwards', 'Female', 'Rwandan'),
('Roger Mueller', 'Male', 'Kenyan'),
('Samantha Reid', 'Female', 'South Sudanese'),
('Tyler Morales', 'Male', 'South Sudanese'),
('Jennifer Acosta', 'Female', 'Kenyan'),
('Jose Wood', 'Male', 'Rwandan'),
('Katherine Hardin', 'Female', 'South Sudanese'),
('Christopher Lopez', 'Male', 'Ugandan'),
('Holly Drake', 'Female', 'Somali'),
('Tanya Mitchell', 'Female', 'Ethiopian'),
('Lee Davis', 'Male', 'Kenyan'),
('Ethan Byrd', 'Male', 'Rwandan'),
('Jamie Mckay', 'Male', 'South Sudanese'),
('Rose Walsh', 'Female', 'Ugandan'),
('Whitney Zamora', 'Female', 'Rwandan'),
('Eric Kramer', 'Male', 'Rwandan'),
('Jane Short', 'Female', 'Somali'),
('Lindsey Cruz', 'Female', 'Kenyan'),
('Terri Frye', 'Female', 'Kenyan'),
('Cory Henson', 'Male', 'South Sudanese'),
('Michael Harris', 'Male', 'South Sudanese'),
('Alex Hebert', 'Male', 'South Sudanese'),
('Ricky Hubbard', 'Male', 'Somali'),
('Jordan Rogers', 'Male', 'Kenyan'),
('Dean Waller', 'Male', 'Rwandan'),
('Darrell Hughes', 'Male', 'Somali'),
('Ryan Duncan', 'Male', 'Ugandan'),
('Tyrone Thomas', 'Male', 'Ugandan'),
('Brandon Moore', 'Male', 'Somali'),
('Michelle Guerrero MD', 'Female', 'Somali'),
('Joshua Williams', 'Male', 'Ugandan'),
('Richard Johnson', 'Male', 'Kenyan'),
('Stephanie Walker', 'Female', 'Ethiopian'),
('Emily Campbell', 'Female', 'Rwandan'),
('Donald Gill', 'Male', 'South Sudanese'),
('Thomas Williams', 'Male', 'South Sudanese'),
('Tyler Alvarez', 'Male', 'Ugandan'),
('Angel Coleman', 'Male', 'Kenyan'),
('Samantha Williams', 'Female', 'South Sudanese'),
('Samantha Martinez', 'Female', 'Ugandan'),
('Heather Morris', 'Female', 'Kenyan'),
('David Flores', 'Male', 'Somali'),
('Tracy Jennings', 'Female', 'Ugandan'),
('Sarah Anderson', 'Female', 'Somali'),
('Barbara Phillips', 'Female', 'Somali'),
('Thomas Walsh', 'Male', 'Ethiopian'),
('William Herrera', 'Male', 'Ethiopian'),
('Debra Mitchell', 'Female', 'Ugandan'),
('Virginia Cabrera', 'Female', 'South Sudanese'),
('Scott Macdonald', 'Male', 'Ugandan'),
('Kathryn Coleman', 'Female', 'Somali'),
('Yvonne Scott', 'Female', 'Ugandan'),
('Savannah Davenport', 'Female', 'Ugandan'),
('Denise Jenkins', 'Female', 'Ugandan'),
('Jonathan Vazquez', 'Male', 'South Sudanese'),
('James Anderson', 'Male', 'Ugandan'),
('Deanna Clark', 'Female', 'Somali'),
('Scott Sanchez', 'Male', 'Ethiopian'),
('Brandon Lozano', 'Male', 'South Sudanese'),
('Kathy Martin', 'Female', 'Ethiopian'),
('Peter Compton', 'Male', 'Kenyan'),
('Jordan Graham', 'Male', 'Ugandan'),
('Michael Johnson', 'Male', 'Ugandan'),
('Charles Sims', 'Male', 'Ethiopian'),
('Julia Lopez', 'Female', 'Kenyan'),
('Monica Tucker', 'Female', 'South Sudanese'),
('Barbara Bass', 'Female', 'Kenyan'),
('Jeff Rhodes', 'Male', 'South Sudanese'),
('Becky Payne', 'Female', 'Somali'),
('Amanda Garcia', 'Female', 'Ugandan'),
('Jake Castro', 'Male', 'Kenyan'),
('Jordan Shea', 'Female', 'Kenyan'),
('Jordan Booth', 'Male', 'Somali'),
('Timothy Moreno', 'Male', 'Kenyan');
